services:
  inventoryservice.webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: inventoryservice.webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
  inventoryservice.database:
    restart: always
    image: postgres:latest
    container_name: inventoryservice.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventorydb
    volumes:
      - ./.containers/inventory-db:/var/lib/postgressql/data
    ports:
      - '5432:5432'
  inventoryservice.migrations:
    image: ${DOCKER_REGISTRY-}migrations
    container_name: inventoryservice.migrations
    build:
      context: .
      dockerfile: Migrations/Dockerfile
    depends_on:
      - inventoryservice.database
    environment:
      - ConnectionStrings__InventoryDb=Host=inventoryservice.database;Database=inventorydb;Username=postgres;Password=postgres
